export const FormKeys = {
    Email: "email",
    Password: "password",
    ConfirmPassword: "confirmPassword",
    FirstName: "firstName",
    MiddleName: "midName",
    LastName: "lastName",
    Phone: "phone",
    Address: "address",
    City: "city",
    Country: "country",
    BuildingName: "buildingName",
    FloorsCount: "floorCount",
    Floor: "floor",
    AptCount: "aptCount",
    AptNum: "aptNum",
    AddInfo: "addInfo",
    OccupantsCount: "occupants",
}